### PR TITLE
Fix GHC 7.10 warnings.

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by afcowie** [comment]
So tempting to just say depends on GHC 7.10, but that would be mean. Or would it?

AfC

**Comment by 23Skidoo** [comment]
In the Cabal project we have a policy of supporting versions of GHC that are up to 3 years old. I think that this a good idea in general.

**Comment by mightybyte** [comment]
We still have production apps running GHC 7.6 with compelling reasons for not having upgraded yet.  Also Snap has a policy of supporting the past three Haskell Platform releases.  So I definitely think compatibility is important.  Although just fixing warnings is maybe not quite as big of a deal.

**Comment by 23Skidoo** [comment]
Spurious warnings are bad because they drown out real ones.

**Comment by afcowie** [comment]
Or we could just add `{-# OPTIONS -fwarn-unused-imports #-}` (or whichever)

AfC

**Comment by 23Skidoo** [comment]
`{-# OPTIONS_GHC -fno-warn-unused-imports #-}`. That's not ideal because you won't be getting such warnings when you decide to change something later.

**Comment by mightybyte** [comment]
Spurious warnings are bad, but if they only show up on older compilers then they're effectively not an issue for developers working on newer compilers.

Also, -fno-warn-unused-imports is not ideal, but conditional compilation with CPP is also not ideal.  So it's a tradeoff.

**Comment by 23Skidoo** [comment]
> Spurious warnings are bad, but if they only show up on older compilers then they're effectively not an issue for developers working on newer compilers.

In this case the warnings show up on GHC 7.10.

> Also, -fno-warn-unused-imports is not ideal, but conditional compilation with CPP is also not ideal. So it's a tradeoff.

Yep.

**Pull request merged**
