### PR TITLE
Allow io-streams-1.3

### PR DESCRIPTION
**Pull request by ddssff**

### CODE REVIEW

**Comment by afcowie** [comment]
I'll merge this, obviously, but I'll need to test it on the release branch first.

AfC

**Comment by ddssff** [comment]
Thanks.  I've built http-streams and the stripe library with this change and all seems well.

**Comment by afcowie** [comment]
Hm. {sigh} What a mess. **io-streams** isn't building right now. It's fixed in 'master' but not published yet. Anyway, so I can't bump the 'release-0.7' branch. As for 'master'...

**Comment by afcowie** [comment]
Done on 'master' and on 'release-0.7'. Uploaded to Hackage as 0.7.2.6. Thanks for the report @ddssff 

AfC

**Pull request merged**
